# Workshop 10

# Plan for today
- Data project follow up
- Linear algebra
- Solving equations analytically
- Problem set 6

# Data project follow up
- Remember to restart the kernel and run all cells before hand in.
- Create functions, do not repeat your code.
- Document your code line by line


<img src="lego_pic.png" style="float:center">

# Linear algebra

# This book in python
<img src="linalg.png" style="float:center">

We use `SciPy's` module `linalg` to perform linear algebra operations: 

- Determinant, invert, norm.
- Solve a system of equations.
- Find eigenvalues.
- Etc.

[Module documentation](https://docs.scipy.org/doc/scipy/reference/linalg.html)

# Example:
$$ Ax = B $$


In [1]:
import numpy as np # import numpy
from scipy import linalg # import linalg

np.random.seed(666) # set seed

A = np.random.uniform(size=(5,5)) # draw random A matrix
B = np.random.uniform(size=5) # draw random B vector

print(f'Matrix A: \n{A} \n\n Matrix b:\n{B}')



Matrix A: 
[[0.70043712 0.84418664 0.67651434 0.72785806 0.95145796]
 [0.0127032  0.4135877  0.04881279 0.09992856 0.50806631]
 [0.20024754 0.74415417 0.192892   0.70084475 0.29322811]
 [0.77447945 0.00510884 0.11285765 0.11095367 0.24766823]
 [0.0232363  0.72732115 0.34003494 0.19750316 0.90917959]] 

 Matrix b:
[0.97834699 0.53280254 0.25913185 0.58381262 0.32569065]


## Example 1.
We use `lu_factor(a[, overwrite_a, check_finite])`, to compute pivoted LU decomposition of A matrix.
Decomposes A into upper and lower triangular matrix and solve through substitution.

And `lu_solve(lu_and_piv, b[, trans, …])`, to solve an equation system, A x = B, given the LU factorization of A.

In [2]:
LU, piv = linalg.lu_factor(A) # compute LU decomposition of A
x = linalg.lu_solve((LU,piv),B) # solve equation system
print(f'x is: {x}')



x is: [-1.09856672 -5.64094348 -3.17432935  5.50035431  4.89126724]


## Example 2
Or the simple way...
`solve(a, b[, sym_pos, lower, overwrite_a, …])`, solves the linear equation set A * x = B for the unknown x for square A matrix.

In [3]:
# Simple solver
x = linalg.solve(A,B)
print(f'x is: {x}')



x is: [-1.09856672 -5.64094348 -3.17432935  5.50035431  4.89126724]


# Solving Equations analytically
We use `Sympy` to work with formulas and model to enable us to translate analytics into python code - Wooow! 


Consider a utility function from a standard OLG model. 

Economic agents lives two periods (young/old) and obtains utility from consumption in both periods:

$$U_{i,t} = u_i(c_{i,1}) + \frac{1}{1+\rho}u_i(C_{i,2})$$

For simplicity we use log-utility.

In [4]:
import sympy as sm # import sympy

c1,c2 = sm.symbols("C_i1"), sm.symbols("C_i2") # define C_i1 and C_i2
rho = sm.symbols("rho") # define rho

#log-utility
uc1 = sm.ln(c1) 
uc2 = sm.ln(c2)
# Define U_it
U = uc1+1/(1+rho)*uc2
U



log(C_i1) + log(C_i2)/(rho + 1)

Let's take the derivative of $U$ with respect to $C_{i,2}$

In [5]:
sm.diff(U,c2)

1/(C_i2*(rho + 1))

🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥

## Sympy can turn your formulas into python functions.
Use the `Lambdify` method which takes a function and an iterable as argument. In our case the function is utility and the iterable is consumption: 

In [6]:
# define utility as a lamba function
util = sm.lambdify((c1,c2,rho),U)

print(f'Utility for C1=10, C2=5 and rho=0.1: {util(10,5,0.1):.2f}')



Utility for C1=10, C2=5 and rho=0.1: 3.77


# Problem set 6
- remember to get the latest version